package filemanager.tablecell.filetable;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class PanelAction extends javax.swing.JPanel {

    public PanelAction() {
        initComponents();
    }
    
    public void initEvent(FileTableActionEvent event, int row){
        redTag.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.redTag(row);
            }           
        });
        blueTag.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.blueTag(row);
            }           
        });
        greenTag.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.greenTag(row);
            }           
        });
        azureTag.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.aruzeTag(row);
            }           
        });
        orangeTag.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.orangeTag(row);
            }           
        });
        yellowTag.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.yellowTag(row);
            }           
        });
        deleteTag.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.deleteTag(row);
            }           
        });   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redTag = new filemanager.tablecell.filetable.Tag_Button();
        blueTag = new filemanager.tablecell.filetable.Tag_Button();
        greenTag = new filemanager.tablecell.filetable.Tag_Button();
        azureTag = new filemanager.tablecell.filetable.Tag_Button();
        orangeTag = new filemanager.tablecell.filetable.Tag_Button();
        yellowTag = new filemanager.tablecell.filetable.Tag_Button();
        deleteTag = new filemanager.tablecell.filetable.Tag_Button();

        setToolTipText("");
        setName(""); // NOI18N

        redTag.setBackground(new java.awt.Color(255, 77, 77));
        redTag.setEffectColor(new java.awt.Color(255, 204, 204));

        blueTag.setBackground(new java.awt.Color(0, 153, 255));
        blueTag.setEffectColor(new java.awt.Color(102, 204, 255));

        greenTag.setBackground(new java.awt.Color(63, 213, 63));
        greenTag.setEffectColor(new java.awt.Color(153, 255, 153));

        azureTag.setBackground(new java.awt.Color(0, 243, 243));
        azureTag.setEffectColor(new java.awt.Color(46, 183, 252));

        orangeTag.setBackground(new java.awt.Color(255, 152, 23));
        orangeTag.setEffectColor(new java.awt.Color(255, 217, 133));

        yellowTag.setBackground(new java.awt.Color(243, 234, 35));
        yellowTag.setEffectColor(new java.awt.Color(202, 187, 0));

        deleteTag.setBackground(new java.awt.Color(114, 114, 114));
        deleteTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filemanager/icon/close_16px.png"))); // NOI18N
        deleteTag.setEffectColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(redTag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(blueTag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(greenTag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(azureTag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(orangeTag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(yellowTag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(deleteTag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blueTag, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(redTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greenTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(azureTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orangeTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yellowTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteTag, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private filemanager.tablecell.filetable.Tag_Button azureTag;
    private filemanager.tablecell.filetable.Tag_Button blueTag;
    private filemanager.tablecell.filetable.Tag_Button deleteTag;
    private filemanager.tablecell.filetable.Tag_Button greenTag;
    private filemanager.tablecell.filetable.Tag_Button orangeTag;
    private filemanager.tablecell.filetable.Tag_Button redTag;
    private filemanager.tablecell.filetable.Tag_Button yellowTag;
    // End of variables declaration//GEN-END:variables
}
